version: '3'

services:
  test7ampache85_squashed:
    build:
      context: .
      dockerfile: Dockerfilephp85
    restart: on-failure
    ports:
      - "18581:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../release-test/7/php85_squashed:/var/www/html/public
      - ./log:/var/log/ampache
      - ./media:/media
      - ./art:/mnt/art
      - ./music:/mnt/music
      - ./podcast:/mnt/podcast
      - ./upload:/mnt/upload
      - ./video:/mnt/video

